Fix Runtime Errors on return to pixi app
Error: Cannot read properties of null (reading 'alphaMode')

So we implemented a better destroy function in the DashboardApp.tsx